"use client";
import "../globals.css";
import { Inter } from "next/font/google";
import React from "react";
import Link from "next/link";
import { DynamicIcon } from "@/components/icon";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  const [scrollY, setScrollY] = React.useState(0)
  React.useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY)
    }
    window.addEventListener("scroll", handleScroll, { passive: true })
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])
  return (
    <html>
      <body
        className={inter.className}
        style={{
          display: "flex",
          gap: "",
        }}
      >
        <div className="bg-gray-200 pt-24 max-sm:hidden">
          <div className="bg-black flex sticky top-[95px] flex-col px-5 py-7 gap-y-14 items-center mx-5 text-white rounded-2xl">
            <p className="font-sans font-extrabold text-4xl ">T</p>
            <Link href="/ekomer">
              <DynamicIcon name="store" size={20} />
            </Link>
            <Link href="/sport">
              <DynamicIcon name="graduation_cap" size={23} />
            </Link>
            <Link href="/sport">
              <DynamicIcon name="trophy" size={20} />
            </Link>
            <Link href="/sport">
              <DynamicIcon name="settings" size={20} />
            </Link>
            <Link href="/sport" className="pt-20">
              <DynamicIcon name="log_out" size={20} />
            </Link>
          </div>
        </div>
        <div>{children}
        
        <Footer />
        </div>
      </body>
    </html>
  );
}
